title: meemow paradise
theme: minima
author: grumble zhao
email: mguo@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  teenage mutant ninja turtles

# social links
twitter_username: doobydoobydoo # DO NOT include the @ character, or else the build will fail!
github_username:  dingerdooger # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
